### ISSUE TITLE
Mails should be sent to the lab specific mail addresses

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/mibi-portal-server#104]
As a portal user I want my data directly to be sent to the associated lab - mail addresses follow by mail.

The config key-value pair 'jobRecipient' . will override the address' retrieved from the database.

**Comment by afalenski** [comment]
NRL email addresses: see email from 05.08.2019@18:05

**Comment by afalenski** [comment]
The epilab02 DB was changed so that it contained different test email addresses. In the epilab02 test system sending mails to lab-specific email addresses worked fine. Done.
This has to be tested again on the productive system as soon as it is deployed.
