### ISSUE TITLE
plausibility check for uniqueness of samples - show warning, not error

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/mibi-portal-server#105]
As a portal user I want to be warned if isolates seem to be the same and I do NOT want to get an error.
A LIMS user would then create "Teilproben" for that

**Comment by dptolle** [comment]
@afalenski : Am I right in assuming this Ticket involves 2 Errors:
1)  "code": 3,
  "level": 2,
  "message": "Probenummer kommt mehrfach vor (bei identischem Erreger).",
2) "code": 6,
  "level": 2,
  "message": "Probenummer nach AVVData kommt mehrfach vor (bei identischem Erreger).",

**Comment by afalenski** [comment]
Done as AAW wanted it.  :-(
