### ISSUE TITLE
Update copyright note to current year

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/mibi-portal-server#107]
@draaw commented on [Tue Feb 26 2019](https://github.com/SiLeBAT/mibi-portal-client/issues/194)

e-mails have a copyright note at the bottom with the last year.
Do also check for other potential occurrences and update them.

**Comment by afalenski** [comment]
Both the email to the NRL and the email to the sender now contain the current year 2019 in the copyright note.

**Comment by afalenski** [comment]
As no occurrences of the current year were found, this ticket is done.
