### ISSUE TITLE
ZSP Warning does not highlight dates

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-server#118]
@afalenski commented on [Mon Apr 15 2019](https://github.com/SiLeBAT/mibi-portal-client/issues/211)

Upload the following testsheet:
[ZSP2019-Tests.xlsx](https://github.com/SiLeBAT/mibi-portal-client/files/3079120/ZSP2019-Tests.xlsx)
The warning says that the combination of ADV2, 3, 8 and year does not match the ZoMo plan. However, the two date columns are not highlighted in yellow. Please fix.

**Comment by GerberI** [comment]
Warning is not added by the server, so i moved this ticket to server board.

**Comment by afalenski** [comment]
Something is wrong with the check: I see the warning and the year is in yellow but when I correct the mistake online and validate again cells stay yellow after validation. This is only the case in QA, not in the productive version of the MiBi-Portal.

**Comment by afalenski** [comment]
All fine now. Done.
