### ISSUE TITLE
Define validation constraints for ZoMo Samples

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/mibi-portal-server#12]
As a MiBi User I want my ZoMo Samples to be validated according to a different Rule set.

**Comment by afalenski** [comment]
I checked different entries which should be recognised as ZoMo 2017 or ZoMo 2018 samples:

Date, ADV2, ADV3, ADV8, expected answer (M = mistake, C = correct)
27.04.2017, 15, 100300, 8000000, C -> error for "100300", probably bug in Matrix Code validation
27.04.2017, 01, 061600, 4000000, C -> OK
27.04.2017, 01, 061600, 1000000, M -> OK
27.04.2017, 15, 003033, 6030230, C -> OK
27.02.2018, 15, 102404, 1010111, C -> OK
27.02.2018, 15, 102404, 8000000, M -> OK
27.02.2018, 20, 202000, 2030120, C -> error for "202000", probably bug in Matrix Code validation
27.02.2018, 01, 063504, 6010000, C -> OK
27.02.2018, 01, 063504, 8000000, M -> OK
27.02.2018, 01, 090800, 6030300, C -> OK
