### ISSUE TITLE
Wrong email template used for admin activation reminder

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/mibi-portal-server#121]
The wrong email template is used when sending an email to the administrators to remind them to activate a user account.

**Comment by afalenski** [comment]
1) There is no link in the reminder. I have to search in the MiBi-Portal emails for the user and - if he/she has tried to register twice or more often I have to compare the affiliation and email addresses. Is this what the admin activation reminder is supposed to look like? What is the intention of leaving out the activation link? 
2) Link validity time: What if nobody has seen the first activation email and - after seven days - the link is not valid anymore? Will I need to talk to a programmer to activate the user account?
Please talk to me.

**Comment by dptolle** [comment]
@afalenski The above commets, although valid, are not in the scope of this bug ticket.  The ticket merely addresses the bug that an incorrect email was sent as a reminder & says nothing about the actual content of the email, which was decided long ago.  If you want the content of the email to change, please create a new User story.

**Comment by afalenski** [comment]
@dptolle My comment (1) is legitimate and this ticket has not been finished properly. The admin activation reminder uses a wrong template because the link is missing. Without a link no admin can activate an account. Please add the link.
About my comment (2) I agree and will write a new ticket.

**Comment by afalenski** [comment]
@dptolle Thanks for the explanation. Ticket done.
