### ISSUE TITLE
Define and document Server API

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/mibi-portal-server#14]
As a Developer I want to be able to review the server API without having to look at the code.

Dev note: Possibly using swagger?

CURRENT API
````
/users
  /login (P: login to Application)
  /register (P: register user)
  /recovery (P: recovery of password???)
  /reset/:token (P: Reset password )
  /activate/:token (P. Activate User account)
  /userdata (P: add user data)
    /:_id (PUT: update user data)
    /:_ids (D: Delete User data)
/api/v1
  /upload (P: Upload to server & trigger KNIME post x2)
  /institutions (G: List of institutions)
````

Maybe see here for inspiration: 
- https://stackoverflow.com/questions/389169/best-practices-for-api-versioning
- https://nordicapis.com/introduction-to-api-versioning-best-practices/

**Comment by afalenski** [comment]
I need a way to test the API.

**Comment by GerberI** [comment]
@Alex
You can test the api via testing the server dependent functionality of the app and by inspecting the network communication via browser dev tools.
You can also test the api via swagger editor, i can show you how it works.
