### ISSUE TITLE
MiBi-Portal changes dates in productive version

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-server#146]
@afalenski commented on [Thu Aug 15 2019](https://github.com/SiLeBAT/mibi-portal-client/issues/292)

Upload the attached Probeneinsendebogen and compare the dates from the Excel sheet with those in the MiBi-Portal. Only dates in row 5 are correct. In the other dates the MiBi-Portal subtracts one day. This is a serious bug and is found in the productive portal, in epilab02 and in nolar. Please consider a hotfix.
[mpc292_Dates-BUG.xlsx](https://app.zenhub.com/files/103999212/13625710-4e82-46f2-85b8-a4fc13053294/download)

**Comment by GerberI** [comment]
Detailed description of bug:
The date/time in the excel sheet has no information about the time zone. Excel and the xlsx library (convert excel to json) use the local system time to interprete a date/time from the excel file. So the date/time 10.1.2019 00:00 gets interpreted as 10.1.2019 00:00 in our local summer time zone UTC+2. The xlsx library then converts this interpreted time in a UTC date/time object. So the 10.1.2019 00:00 interpreted in summer time is converted to 9.1.2019 23:00 UTC+1 at winter time perhaps because the date lies in winter.
The other way arround: The date/time 9.1.2019 23:00 UTC+1 is now in our local summer time zone the 10.1.2019 00:00 UTC+2.
For a non human entity it is not relevant if the date is 9.1.2019 23:00 UTC+1 or 10.1.2019 00:00 UTC+2. To fix the bug i converted the UTC+1 time back to the local server time (now the summer time UTC+2).
In future we should rely on date/time objects with UTC format to be independent of time zones and only convert at user interfaces to local time zones and human readable formats.

**Comment by afalenski** [comment]
Great! Thank you for fixing this bug immediately! All tested dates are correct now. Done.
