### ISSUE TITLE
New warning: Data says it is a ZoMo sample

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/mibi-portal-server#157]
@afalenski commented on [Mon Feb 18 2019](https://github.com/SiLeBAT/mibi-portal-client/issues/191)

As an analyst I would like all ZoMo samples to be defined as ADV4-code = 81 ("Zoonosen-Monitoring - Planprobe"). If a MiBi-Portal user uploads data which comply with the ZoMo sample rules but gives as reason any other ADV4-code (e.g. code 10 = "Planprobe") both ADV4 cells should be coloured in yellow and show the warning "Ihre Daten passen zum Zoonosen-Stichprobenplan. Bitte prüfen Sie noch einmal, ob Sie nicht als Grund Code 81 bzw. Text "Zoonosen-Monitoring - Planprobe" angeben sollten."

**Comment by afalenski** [comment]
Works very well, both with ADV4 codes and texts. Great job! Done.
