### ISSUE TITLE
Improve User Registration

### ISSUE THREAD

**Issue by birgitlewicki** [SiLeBAT/mibi-portal-server#16]
As a registered User I want to receive a new Activation email if I attempt to log on without being activated.

DevNote: Message should read: "Not authorized or not activated. If already registered, please check your email for an activation code".

**Comment by draaw** [comment]
Still does not work on epilab.bfr.berlin. Using my old account (gmail):
- I do not get an activation email
- when trying to register with this mail - nothing happened; no mail, no feedback in the frontend

**Comment by draaw** [comment]
ok, the activation mail arrives, thats fine.
But when trying to register with an already registered email, there is no feedback in the frontend. Is that correct?

**Comment by dptolle** [comment]
Now displaying following alert at the frontend: "Registration failed. Please contact support: <support-email>"

**Comment by dptolle** [comment]
Implemented & pushed to develop: requires deployment to proceed.
