### ISSUE TITLE
Assign Users to institutes

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/mibi-portal-server#164]
~~remove inactive users without institute if older than X days~~
In ticket mibi-portal-server#111 the institute 'dummy' was deleted. However, there are 7 active users to which this 'institute' is still assigned. Please assign the correct institutes to these users. See email attachment (columns A-C and H) from AF from 30.09.2019@08:13.

**Comment by afalenski** [comment]
The corrections are fine, thank you!
However, there is still a user (a test account) in the productive DB with the 'dummy' institute. All dummy institutes shall disappear. 
- [ ] Delete the user and then 
- [ ] delete the institute 'dummy'.
See internal comment sent by AF via email from 27.10.2019@17:38.

**Comment by dptolle** [comment]
@afalenski Deleting invalid user & dummy institute was not part of the Ticket scope - please do not change Ticket scope mid-sprint

**Comment by afalenski** [comment]
Thank you for deleting despite being not part of the ticket. Done.
