### ISSUE TITLE
DB Access for Master Data

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-server#180]

**Comment by afalenski** [comment]
Tested:
Registration with 10minutemail: 
- activation email received
- activation by button successful
- admin activation email received
- admin activation by button successful
- info email that user can login received
- user login successful
- sending data successful
-- NRL email received, XLSX attachment available and correct
-- user email received, attachment available and correct
- reset password tested
-- email received, button pushed
-- reset successful, login with new password successful
