### ISSUE TITLE
ReceiveAs param of API PostSubmitted Enpoint uses number instead of string

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-server#186]
The API PostSubmitted endpoint doesnt work as specified in the swagger docu.
Instead of posting an order with receiveAs="PDF" / "EXCEL" the user must post and order with receiveAs="0" / "1".

Dev-Note:
This is because of wrong use of typescript enums .toString() function. It converts the value of the enum not the key. Use Enum[key] to get a string representation of the enum.

Server should accept both variants.

Fix affects client and server.

**Comment by afalenski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MiBi-Portal-5a817089b72527484e410a5a/issues/SiLeBAT/mibi-portal-server/186?planning-poker) with ZenHub @bfrgottscma @birgitlewicki @GerberI

**Comment by afalenski** [comment]
Outdated.
