### ISSUE TITLE
E-Mails need to be in German as well

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/mibi-portal-server#20]
@draaw commented on [Tue Mar 13 2018](https://github.com/SiLeBAT/epi-lab-client/issues/53)

As a Mibi-portal user I want to read my mails in German

**Comment by dptolle** [comment]
Implemented & pushed to develop: requires deployment to proceed.

**Comment by draaw** [comment]
German text is very nice.
Following minor suggestions:
- "Sicherheitsbezogen: Diese Anfrage wurde von localhost:3000 mit Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36 gesendet. " -> remove "von localhost:3000".
- remove "Mit freundlichen Grüßen,"
- exchange "Hi <username>" -> "Liebe(r) "
