### ISSUE TITLE
Server response does not contain oldValue if oldValue is empty string

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-server#202]
The server should respond with the oldValue set to "" if the request contained oldValue="". As of now the server responses with oldValue not set at all. This affects submitted and validated endpoint.

**Comment by GerberI** [comment]
@Alex
Testable by editing an empty field and validate or send the data. The field should keep the a blue border now.

**Comment by afalenski** [comment]
The blue border is still there after editing and validating. Done.
