### ISSUE TITLE
Parsing data from sample sheet header is buggy

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-server#210]
See description in the Epic.

Dev-Note:
Write a common parsing algorithm interpreting the type of a cell and converting to string accordingly.

**Comment by GerberI** [comment]
I've implemented following parsing rules for the different cell types:
* Boolean => 'WAHR' or 'FALSCH'
* Error => english error code
* Number => integer or comma separated fractional, all custom number formats are ignored and converted to the mentioned format
* Date => 'dd.mm.yy' for date, 'hh:mm:ss' for time, 'dd.mm.yy hh:mm:ss' for date and time, all other custom date/time formats are ignored and converted to the mentioned formats
* String => same string with removed leading and trailing white spaces

**Comment by afalenski** [comment]
I could test number, date and string and in all cases the code worked. Done.
