### ISSUE TITLE
Update all server libraries

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-server#221]

**Comment by GerberI** [comment]
@afalenski 
Things you could test explicitly before the release QA tests:
- The pathogen autocorrection suggestions have changed. The found results may differ from the previous version. Please compare to productive portal and check if differences make sense. Besides the results are now sorted first by priority and then alphabetically.
- I'd have to rewrite the timezone dependent excel parsing code (our xlsx library introduced a new bug...). So please check if dates are correct concerning the timezones (only summertime is possible to test).

**Comment by afalenski** [comment]
Pathogen correction lists: Fantastic! Better than the old version. Nearly always the first correction suggestion was the one that was meant in the wrong pathogen text. And there are sometimes just two entries, sometimes ten, but the correct one was always available.
Dates: No changes in dates compared to the Excel sheet could be found.
Done.
