### ISSUE TITLE
Add new institute: "Niedersächsisches Landesamt für Verbraucherschutz und Lebensmittelsicherheit"

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-server#231]
As a user i would like to register with the web-app as  "Niedersächsisches Landesamt für Verbraucherschutz und Lebensmittelsicherheit".

Db-Entry:
{
   "name1": "Niedersächsisches Landesamt für Verbraucherschutz und Lebensmittelsicherheit",
   "name2": "-Futtermittelinstitut Stade-",
   "location": "21680 Stade",
   "address1": {
       "street": "Heckenweg 6",
       "city": "21680 Stade"
   },
   "phone": "0 41 41 93 36",
   "fax": "0 41 41/ 93 37 77",
   "email": [
       "poststelle@laves.niedersachsen.de"
   ],
   "state_id": ObjectID("5b0ea59f43032d2a9d15688e"),
   "state_short": "NI",
   "city": "Stade",
   "zip": "21680"
}

**Comment by GerberI** [comment]
@afalenski 
Hab mal ein Ticket erstellt

**Comment by GerberI** [comment]
@afalenski 
That's what gets added to the DB (without location, address1 and state_id):
{
    "email" : [ 
        "poststelle@laves.niedersachsen.de"
    ],
    "name1" : "Niedersächsisches Landesamt für Verbraucherschutz und Lebensmittelsicherheit",
    "name2" : "-Futtermittelinstitut Stade-",
    "phone" : "0 41 41 93 36",
    "fax" : "0 41 41/ 93 37 77",
    "state_short" : "NI",
    "city" : "Stade",
    "zip" : "21680",
}

**Comment by GerberI** [comment]
@afalenski 
dominic confirmed it, location, address1 and state_id are from the time where birgit added the institutes to the db. There are not used by our code and the db update scripts ignore them. So he also stated that they might become relevant if we add the feature to apply the institute automatically to the sample sheets. Then we have to reintroduce at least the detailed address to the db.

**Comment by GerberI** [comment]
@afalenski 
Please test registering, login and the profile page on QA, then i will apply the changes to Production and you can test it there again (or let the new user test it for you ;).

**Comment by afalenski** [comment]
The new institute is in the institute list and can be selected. Registering worked, confirmation email was sent to user. However, no admin activation email was sent to the MiBi-Portal mailbox within 10 minutes.
