### ISSUE TITLE
Update all Server- and Data Production Libraries

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-server#243]
**Server-Production**
pre-release: (pdfmake), (xlsx)
major: (express-jwt), helmet
minor: inversify, nodemailer, moment

**Shared-Production**
pre-release: (argon2)
minor: mongoose

**Comment by GerberI** [comment]
mongoose can only be updated up to version 5.10 because mongoose plugin mongoose-unique-validator is not maintained anymore and conflicts with newer versions.

Dev-Note: Since version 5.11 mongoose integrates its own types for typescript, mongoose-unique-validator still uses the old external type library for mongoose. So all types are declared twice and in different ways making it impossible to build the project.

**Comment by GerberI** [comment]
@afalenski 
Things to test:
- Database related things like user registration and login
- The http security headers where updated, so please clear the browser cache and check if any errors are shown in console and network developer tools and if all links are working
- Generated excel and pdf sheets
- The autocorrection lib fuse.js had a breaking change, so the autocorrection offers are different now. Actually they fixed a bug so that the order of the suggestions is now more like i intended them to be:
Before update:
![alt.png](https://images.zenhubusercontent.com/5c35c98c4b5806bc2b01ed72/88e2fa8d-c5b7-411e-85ad-a1e845c83bd3)
After update:
![neu.png](https://images.zenhubusercontent.com/5c35c98c4b5806bc2b01ed72/d05798bb-f43a-4f10-929a-86bca915b9b1)
So please check some corner cases if the suggestions are still useful.

**Comment by afalenski** [comment]
After clicking "Registrieren", it was not possible to click on "Anmelden"; clicking on "Probendaten" worked. When the toaster was closes (click on "Schließen", it was possible to click on "Anmelden". Browser console text "Content Security Policy: Unbekannte Direktive 'script-src-attr' kann nicht verarbeitet werden"
After clicking on the activation link in the email: additional errors:
_Content Security Policy: Unbekannte Direktive 'script-src-attr' kann nicht verarbeitet werden
Angular is running in the development mode. Call enableProdMode() to enable the production mode. core.js:38781
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'isBanner: [object Object]'. Current value: 'isBanner: true'.
    Angular 7
        viewDebugError
        expressionChangedAfterItHasBeenCheckedError
        checkBindingNoChanges
        checkNoChangesNodeInline
        checkNoChangesNode
        debugCheckNoChangesNode
        debugCheckDirectivesFn
    View_PageBodyContainerComponent_0 PageBodyContainerComponent.html:1
    Angular 23
        debugUpdateDirectives
        checkNoChangesView
        callViewAction
        execComponentViewsAction
        checkNoChangesView
        callViewAction
        execComponentViewsAction
        checkNoChangesView
        callViewAction
        execComponentViewsAction
        checkNoChangesView
        callWithDebugContext
        debugCheckNoChangesView
        checkNoChanges
        tick
        next
        invoke
        onInvoke
        invoke
        run
        run
        next
        schedulerFn
    RxJS 5
        __tryOrUnsub
        next
        _next
        next
        next
    Angular 11
        emit
        checkStable
        onHasTask
        hasTask
        _updateTaskCount
        _updateTaskCount
        runTask
        drainMicroTaskQueue
        invokeTask
        invokeTask
        globalZoneAwareCallback
PageBodyContainerComponent.html:1
ERROR CONTEXT 
Object { view: {…}, nodeIndex: 1, nodeDef: {…}, elDef: {…}, elView: {…} }
PageBodyContainerComponent.html:1
    View_PageBodyContainerComponent_0 PageBodyContainerComponent.html:1
    Angular 16
        proxyClass
        logError
        handleError
        tick
        invoke
        run
        runOutsideAngular
        tick
        next
        invoke
        onInvoke
        invoke
        run
        run
        next
        schedulerFn
    RxJS 5
        __tryOrUnsub
        next
        _next
        next
        next
    Angular 11
        emit
        checkStable
        onHasTask
        hasTask
        _updateTaskCount
        _updateTaskCount
        runTask
        drainMicroTaskQueue
        invokeTask
        invokeTask
        globalZoneAwareCallback_
Logging in after registration was possible without other errors.

**Comment by GerberI** [comment]
Thx for the detailed testing. A few things:
- After registration click, anmelden click not possible:
I do not understand this, if i register and click "Registrieren" i get to the "Anmelden" page, then i can click on "Anmelden" next to "Probendaten" but nothing happens because i am already on the login page. Can you please describe the problem in more detail?
-script-src-attr:
 I will remove this content policy because it is not supported by firefox
- Angular debug warning after clicking activation link:
This warning was also there before the lib update, i will make a ticket for that because fixing those warning can be a bit complicated.
- Autocorrection click causes white screen:
Can you please check this again on production, after a restart and with a different browser? I can not reproduce it. What exact part of the screen becomes white
- Missing "Datenschutz" link:
Ok, you can put it to the other "Datenschutz" ticket.

**Comment by afalenski** [comment]
- Autocorrection: Seems to be a Firefox problem (version: see above), could not reproduce in Chrome; 
To reproduce:
- Upload the file [https://app.zenhub.com/files/121366790/70f65900-c368-4a7c-9b62-57aff6453cbf/download](https://app.zenhub.com/files/121366790/70f65900-c368-4a7c-9b62-57aff6453cbf/download)
- Double click onto "Salmonella Agonar" in row 136 and select an entry (in my case: no white screen)
- Double click into the next pathogen cell in row 137, select an entry (white screen for half a second)
- Double click into the next pathogen cell in row 138, select an entry (white screen for half a second)
- Double click into the next pathogen cell in row 139, select an entry (white screen for half a second)
When I go on row for row there are some rows where no white screen appears and then it starts again.
It was not possible to get a screenshot, but the blue and light blue menu bars as well as the footer stay visible, only the table becomes white for a brief moment (like a slow refresh).
- [x] Datenschutz link: Ticket mpc#416 edited

**Comment by GerberI** [comment]
Autocorrection white screen:
I've tested it on the same system but could not reproduce the problem. The table keeps stable while editing the fields. But in my firefox the header flickers during scrolling a large table. All these visual artifacts have to do how fast the browser is able to render the table (and how the browser's rendering engine works). So the rendering could be faster on the release candidate where the client is compiled with production mode (that could explain why you can't see the blank page on our productive system.) So you could test it then again.
Second: After updating Angular to v9 the issue could be solved because they switch angular's rendering engine.
Third: After any firefox update the issue could be gone, if they change their browser rendering engine.
In general most dynamic web based apps have these problems, so i would suggest to ignore those issues as long as they do not affect the usability.
If you like you can create a ticket addressing the rendering issues, to keep track of them.

**Comment by afalenski** [comment]
Will be watched and is now part of another ticket.
Done.
