### ISSUE TITLE
Make superscript annotations in pdf sample sheet visually more appealing

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-server#245]
As a user i would like to have the best visual experience by looking at the documents generated by the mibi-portal.

Dev-Note: pdfmake has introduced a superscript and subscript feature, so the present manual placement of the superscript annotations can be replaced by the more easier to use and more visual appealing built in superscripts.

See: https://github.com/bpampuch/pdfmake/pull/2128/files

**Comment by afalenski** [comment]
The superscript letters look much more 'natural', are at a better position compared to before and have all a size fitting to the font. Very good! 
Links in PDF work, structure is good.
Done.
