### ISSUE TITLE
Add ZSP2022

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-server#268]
+ Update zsp integration test

**Comment by afalenski** [comment]
Tested.
- Login, data upload, validation, online correction works.
- Test data sent to BfR at 08:45; user email received at 08:52; NRL email received at 08:45;
ZSP integration successful. Done.

______
**Tested with**
OS: Windows 10

Datasets: 
MiBi-TEST_Error-Codes_B_ZSP.xlsx

Browsers:
- Firefox 78.15.0esr (64-Bit)
