### ISSUE TITLE
Establish a password strength checker module

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/mibi-portal-server#27]
@draaw commented on [Sat Mar 31 2018](https://github.com/SiLeBAT/mibi-portal-resources/issues/2)

As a Portal user I want to have a very good password. I would also like to be informed when the password may have been hacked already.

Note:
- consider all pwned passwords - download and regularly update that db (https://haveibeenpwned.com/Passwords)
- take care of the new NIST recommendations, e.g. https://auth0.com/blog/dont-pass-on-the-new-nist-password-guidelines/

**Comment by birgitlewicki** [comment]
Implemented.
Ready for deployment.
