### ISSUE TITLE
DDD: Write unit tests for domain objects

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-server#279]

**Comment by afalenski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MiBi-Portal-5a817089b72527484e410a5a/issues/SiLeBAT/mibi-portal-server/279?planning-poker) with ZenHub @bfrgottscma @GerberI @MicheleK17 @ruegenbfr

**Comment by GerberI** [comment]
Cancelled
