### ISSUE TITLE
Include pathogen in sample validation against ZSP

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-server#282]
As a ZoMo data analyst I want all samples which are marked with ADV4 code 81 "Zoonosen-Monitoring - Planprobe" to comply with the ZSP and thus the pathogen needs to be checked in addition. This check has not been included so far.

- Include pathogen in validation against ZSP (match pathogen ~abbreviation~ code to code of given pathogen, check whether the combination of ADV2, 3, 8 and 16 is part of ZSP)
- Replace ZSP2022_20220113.csv by new ZSP2022 CSV file including pathogen (see email to BL on 16.12.2022@15:13)
- Remove ZSP2021 and older from MiBi-Portal
- Please change error text for error 49:
Old: "Kombination aus ADV2-Code, ADV3-Code, ADV8-Code und Jahr passt zu keinem Zoonose-Monitoring-Programm"
New: "Kombination aus Erreger, ADV2-Code, ADV3-Code, ADV8-Code und Jahr passt zu keinem Zoonose-Monitoring-Programm"
- Add warning also to ADV2 column (column 10)

- This changed error message is valid for columns:
Old: 11;14;15;16
New: 3;5;6;10;11;14;15;16

Dev-Notes:

Master-Data:

- Adjust validation error message in database
- Add migration function to test fixture array

Server:

- Adjust catalog repository => zsp to read new columns in condensed format (see new zsp)
- Add validation code to registerZomo custom validator

**Comment by afalenski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MiBi-Portal-5a817089b72527484e410a5a/issues/SiLeBAT/mibi-portal-server/282?planning-poker) with ZenHub @bfrgottscma @GerberI @MicheleK17 @ruegenbfr

**Comment by afalenski** [comment]
Pathogen: Please see my email from 15.09.2022@16:31
About the valid columns: Yes, correct.

**Comment by afalenski** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MiBi-Portal-5a817089b72527484e410a5a/issues/SiLeBAT/mibi-portal-server/282?planning-poker) with Zenhub @birgitlewicki

**Comment by birgitlewicki** [comment]
Requested features are implemented and deployed on qa.

Remark:
-  Currently on qa the ZSP for 2023 is loaded with the new condensed format and can be tested.
-  On qa no ZSP for 2022 is loaded, therefore ZSP samples for 2022 cannot be tested
-  The ZSPs older than 2022 are removed, samples for these years can also not be tested anymore
-  As soon as the correct ZSPs for 2022 and 2023 with the condensed csv format are available they will be loaded on the qa system.

**Comment by birgitlewicki** [comment]
The final versions of ZSP2022.csv and ZSP2023.csv created with Knime Workflow are deployed on qa and can be tested.
The ZSP should contain now all Salmonella.

**Comment by afalenski** [comment]
Pathogen is included in test against ZSP in the productive ADV MiBi-Portal.
Done.
