### ISSUE TITLE
Parse: Make dashboard available

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-server#292]
Make the parse dashboard available via the admin endpoint. It should be hosted with vanilla settings and no access restrictions.

- Install parse server with sufficient configuration
- Install dashboard with sufficient configuration
- Replace mongo-express with parse server and dashboard in start script

Deploy on Nolar-Dev

**Comment by afalenski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MiBi-Portal-5a817089b72527484e410a5a/issues/SiLeBAT/mibi-portal-server/292?planning-poker) with Zenhub @birgitlewicki @GerberI @ruegenbfr

**Comment by birgitlewicki** [comment]
The Parse Dashboard is now available at

https://nolar-dev.bfr.berlin/admin

As before with mongo-express it is only reachable from the intranet, not from extern.

**Comment by afalenski** [comment]
- Dashboard is visible.
- Class with columns can be added
- Row can be edited via right click -> edit row
- Log shows deprecation warning
- MongoExpress is not replaced.
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Browsers:
- Firefox 91.13.0esr (64-Bit)
