### ISSUE TITLE
Parse: Prepare DB migration

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-server#295]
To migrate the DB to be compatible with parse, some research has to be done.

**Object ids**

Parse-server uses/requires type **string** for primary keys (attribute **_id**) in collections but our mongo db collections are using type **ObjectId**. ObjectIds can be auto created, string ids not.

Read: [ObjectId in MongoDB](https://docs.mongodb.com/manual/reference/bson-types/#objectid)

- What exact id format to use? Parse server, mongoose or mongoDB format?
- Is there a possibility to auto generate string ids via mongoose, mongoDB driver or parse server?
- Are migrated ids compatible with parse-server and mongoose?
- Does the parse server or mongoDB check for uniqueness of keys?

**"created" and "updated" fields**

**createdAt** and **updatedAt** fields should be renamed to **_created_at** and **_updated_at** because the parse-server uses these fields.

- Is the current date format compatible with parse server?

**Revision keys**

Avoid/Rename field names starting with '**`_`**' except the ones mentioned above. Currently only '**`__v`**' is used (auto created by mongoose as revision counter).

Read: [versionKey in  mongoose](https://mongoosejs.com/docs/guide.html#versionKey)

- Are the revision keys necessary for mongoose or can they be disabled/removed?

**Indexing**

- Check if mongoose indexing is compatible with parse-server.
- How and when are the indices created/updated by mongoose, parse server and mongoDB?
- Perhaps indexing can be disabled (we have small databases).

**Comment by birgitlewicki** [comment]
Results of this ticket are described at https://gitlab.bfr.berlin/devs43/common/parse-integration/-/wikis/Using-parse-server-with-existing-mongo-db-collections
