### ISSUE TITLE
Update mongoose to v6

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-server#302]
Has breaking changes

**Comment by GerberI** [comment]
Unable to update to newest version in server repository due to incompatible typescript version (mongodb sub dependency requires newer typescript version).

**Comment by GerberI** [comment]
@afalenski 
Please test all db related task (registering a new user, login, validation errors, analysis procedures selection during sending).

**Comment by afalenski** [comment]
- Login works
- Validation errors for pathogens are shown and alternative suggestions are given
- Validation errors for ADV2, 3, 4, 8, 9 and 12 work
- Selecting another lab in the wizard works, message box opens when selecting "sonstiges" or "Vergleiche mit humanen Isolaten
- "Senden" dialogue appears after wizard, counter shows how many characters can be typed

Registering a new user 
- [x] email confirmation
- [x] admin activation (email received after 11 minutes)
- [x] user email received, link to login works
- [x] new user login works
