### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-server#305]
Major updates
- express-jwt, helmet (not used), xlsx, lint-staged

Minor updates
- @SiLeBAT/fg43-ne-server, express, fuse.js, nodemailer, pdfmake
- swagger-ui-express, winston, jest, prettier, ts-jest

Removed
- @types/express-jwt, @types/helmet

Also
- Set log level to "error" for unit tests

**Comment by GerberI** [comment]
@afalenski 
Things to check: login, excel import/export and exported xlsx file, sent pdf file, email activation or pw reset links

**Comment by afalenski** [comment]
- [x] Login: Old login does not work and cannot be restored ("passwort vergessen" does not work with this email address.) Registering anew and login with new account works.
- [x] Excel upload: Works fine
- [x] Excel export: Works fine
- [x] Exported xlsx file: Looks good, is complete
- [x] Wizard and Senden windows: Look good, are complete
- [x] Sent pdf file: Looks good, is complete
- [x] Sent xlsx file: Looks good, is complete
- [x] Email activation: Links in emails (user and admin) work, new registry is possible
- [x] Password reset link: Button works, reset link in email works, login after reset possible
Great! Done.

______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
Einsendebogen-v15_NRL-AR_TEST.xlsx

Browsers:
- Firefox 91.7.0esr (64-Bit)
