### ISSUE TITLE
Persist: Develop DB schema for order-list

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-server#306]
A mongoose schema has to be developed to store the order-list in the mongodb.

To think about: How to store the data in the most efficient and secure way. Perhaps read best practices docs for mongo-db.

Dev-Note:
- Add the new schema to master-data and server repos

**Comment by afalenski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MiBi-Portal-5a817089b72527484e410a5a/issues/SiLeBAT/mibi-portal-server/306?planning-poker) with ZenHub @bfrgottscma @GerberI @ruegenbfr

**Comment by afalenski** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MiBi-Portal-5a817089b72527484e410a5a/issues/SiLeBAT/mibi-portal-server/306?planning-poker) with ZenHub @birgitlewicki

**Comment by GerberI** [comment]
Moved to #321
