### ISSUE TITLE
Reset Password: If email is unknown, there is no feedback on webpage and no email is sent

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-server#32]
At https://epilab.bfr.berlin/users/recovery you can reset your password. However, if the system does not know your email address, no email is sent and no information is given on the webpage.

**Comment by draaw** [comment]
How can it happen that the system is not aware of your email address?
It is a required field and you do your login with it.

**Comment by afalenski** [comment]
The system does not "know" the email address because it differs capital letters from lower case letters in the email address... which is highly unusual. In addition, I would like to complement this bug ticket: I think in any case the webpage should inform the user that an email has been sent to the given address for password recovery. At the moment nothing happens.

**Comment by draaw** [comment]
But the ticket with case sensitivity is #33?!? So this can be closed again?

**Comment by birgitlewicki** [comment]
The system is not aware of your email address in the case

- a person never registered and goes straight to the password recovery option

- currently the search for the email address in the db is case sensitive; therefore a user is not found if he enters his email address in a different case than during registration

**Comment by birgitlewicki** [comment]
Fixed:

- if the email address is unknown to the system the user is informed that a mail has been sent to the given address

- the email search now is case-insensitive

**Comment by birgitlewicki** [comment]
If the email is unknown to the system the password recovery process should not send a mail to the unknown address. Instead the message should not indicate if the email is known or unknown to the system. Only if the email is known a mail with the password reset link should be sent.

**Comment by draaw** [comment]
Right now the "toaster" shows the following text: "Eine Email mit weiteren Anweisungen wurde an <mail-address> gesendet". Please change it to: "Eine Email mit weiteren Anweisungen wurde an <mail-address> gesendet. Wenn Sie keine Email erhalten, könnte das bedeuten, daß Sie sich mit einer anderen Email-Adresse angemeldet haben".
Additionally, an email is only sent to a known mail address.

**Comment by birgitlewicki** [comment]
Fixed.
Ready for deployment.
