### ISSUE TITLE
Persist: Define API for order-list

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-server#320]
The API endpoint for getting the order-list must be defined.

An authenticated user gets a list of previously sent orders. It should contain order-id, filename and date.

Note:
- The API should be defined ready for implementation.
- No swagger definition necessary yet.
- The API is none public for now.

**Comment by afalenski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MiBi-Portal-5a817089b72527484e410a5a/issues/SiLeBAT/mibi-portal-server/320?planning-poker) with Zenhub @birgitlewicki @GerberI @ruegenbfr

**Comment by GerberI** [comment]
Moved to SiLeBAT/mibi-portal-client#493
