### ISSUE TITLE
Update argon2

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-server#326]
Update argon2 to newest version (server/data).

Also update minor production dependencies for server/data:
- nodemailer, pdfmake, swagger-ui-express, winston

**Comment by GerberI** [comment]
Removed custom argon2 configuration in favor of recommended default configuration

**Comment by GerberI** [comment]
@afalenski 
Things to test: Sending e-mails, optics of multi-paged sample sheet pdf

**Comment by afalenski** [comment]
- Login works
- Emails are sent: 1st Register email, password reset, sending sample data (PDF ans XLSX)
- Multi-paged sample sheet PDF looks good
- Separation of one sample sheet with two pathogens to two sample sheets for different labs works
Done.
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
Mibi-Portal-Testdatei100_ohneFehler.xlsx

Browsers:
- Firefox 91.13.0esr (64-Bit)
