### ISSUE TITLE
Add new ADV catalogs

### ISSUE THREAD

**Issue by birgitlewicki** [SiLeBAT/mibi-portal-server#332]
As a user I would like the MiBi-Portal to support the latest ADV catalogs for Jan 2023.

Please exchange the current catalogs against the new ones and adapt the RegEx rules as indicated in Excel sheet (see email 08.01.2023@07:56).

**Comment by birgitlewicki** [comment]
Ticket implemented, data deployment on qa
=> Alex test ok (mail 10.01.2023@8:24

**Comment by afalenski** [comment]
ADV tests worked without errors in the productive portal.
Done.
