### ISSUE TITLE
Create 2 new institutes in DB

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-server#337]
As a future MiBi-Portal user I would like to register with my institute. This is currently missing.

Enter 2 new institutes.

JSON-Text with corrected entries: See email to BL on 14.03.2023@13:17

**Comment by birgitlewicki** [comment]
Hotfix deployed on qa for testing.

**Comment by afalenski** [comment]
As written on 16.03.2023@08:27
Great, I can select the institutes now.
Quicktest of key functionalities was successful.
Done
