### ISSUE TITLE
Import, parse and store the AVV catalogs 303, 313, 316, 319, 322, 324, 326, 339

### ISSUE THREAD

**Issue by birgitlewicki** [SiLeBAT/mibi-portal-server#339]
master-data:

Development of a script that imports/parses the AVV xml catalogs 303, 313, 316, 319, 322, 324, 326, 339 and stores the data in json files.

**Comment by birgitlewicki** [comment]
The transformation of the seven avv catalogs 303, 313, 316, 319, 322, 324, 326, 339 to a json catalog structure are implemented

**Comment by afalenski** [comment]
As AVV codes are checked when an Einsendebogen is uploaded, the parsing of AVV catalogues is obviously very successful.
Done.
