### ISSUE TITLE
Clicking on "Download" after sending promts no file. Empty browser after reload

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-server#34]
I uploaded my test file
[Mibi-Portal-Testdatei.xlsx](https://github.com/SiLeBAT/mibi-portal-server/files/2072857/Mibi-Portal-Testdatei.xlsx), corrected mistakes and sent the content to BfR via "senden". Afterwards I clicked on "Download" but nothing happened. When I clicked on refresh (F5) to refresh the webpage it became empty.

**Comment by birgitlewicki** [comment]
I cannot reproduce this bug. Clicking 'download' opens a file dialog where the excel sheet can be locally saved. It might take a moment until the dialog opens because it needs time to export the table data to the excel sheet.

**Comment by draaw** [comment]
Did you sent it before trying to download it?

**Comment by birgitlewicki** [comment]
Not reproducible.
