### ISSUE TITLE
Validate excel sheet data against the new xml AVV DatA catalogs 303, 313, 319, 322, 324, 326, 339

### ISSUE THREAD

**Issue by birgitlewicki** [SiLeBAT/mibi-portal-server#345]
As a user I would like to be able to validate my excel sheet against the new AVV DatA 303, 313, 319, 322, 324, 326, 339 catalogs that were transformed to json files.

For this the validation routines have to be adapted to the new json catalog structures.

**Comment by birgitlewicki** [comment]
- Transformed xml catalogs to json in a O(1) search friendly format
- - pushed to branch

**Comment by afalenski** [comment]
All catalogues implemented, in addition also 316 and 328.
Catalogues 324, 319, 316 and 328 need to be updated, will be done in mps348.
Done
