### ISSUE TITLE
Refactor main script to prepare for parse cloud code

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/mibi-portal-server#346]
@dptolle commented on [Wed Jun 28 2023](https://github.com/SiLeBAT/mibi-portal-client/issues/522)

**Comment by birgitlewicki** [comment]
After merging this to develop:
- the nightly build does not run on qa
- the libraries needs to be updated in order to have 0 vulnerabilities with 'npm audit --omit=dev'
- npm run test (= jest tests) throwing errors and need to be fixed
