### ISSUE TITLE
Implement new excel v17 structure

### ISSUE THREAD

**Issue by birgitlewicki** [SiLeBAT/mibi-portal-server#351]
As a user I would like to validate the new excel sheet v17. It has 21 columns, the header texts are adopted to the new AVV catalogs. In the first step the validation of non ZoMo samples should be implemented.

For mockup see mail from 03.08.2023

**Comment by birgitlewicki** [comment]
- Preliminary Excel v17 structure implemented in server and client
- Excel v17 added to master-data 
   => Export of Excel Sheets works correctly, check data formats in cells of exported sheet
- column header text according to the Excel v17 structure with small changes
- renamed column names in server code that they fit to avv names and new header text
 
**question to discuss:**

how to check ZoMo sample?
currently implemented:
- Kode in `control_program_avv` = 70564|53075| (avv catalog 322)
- Kode in `sampling_reason_avv`: not taken into account
- Text in `program_reason_text`: should **contain** 'Zoonosen-Monitoring'

**Comment by afalenski** [comment]
Done.
