### ISSUE TITLE
Adapt the validation error messages to the new AVV DatA catalogs

### ISSUE THREAD

**Issue by birgitlewicki** [SiLeBAT/mibi-portal-server#353]
As a user I would like to get the appropriate validation error messages when validating my excel sheet v17 with the new AVV DatA catalog codes.

The new messages of the validation errors are listed in validationerrors_20231021.xlsx see mail from AF on 22.10.2023.

The corresponding changes will be done by adding a migration-function in master-data.

**Comment by afalenski** [comment]
- My fault: I forgot to specify that for error 34 either Tier or Matrix code is obligatory (and giving both is of course also fine). At the moment the user gets an error if Tier code is present / Matrix code is missing and vice versa.

**Comment by afalenski** [comment]
- Before the AVV catalogue update in the portal all validation errors except Programm, ZoMo and Betriebsart were tested and active. 
- After the AVV catalogue update Betriebsart and Programm were tested ant active, but there is now a problem with the Tiere and Matrix codes. 
- ZoMo validation errors cannot be tested as they are currently inactive.

All validation errors except for those concerning ZoMo will be tested after the catalogue problem is fixed (see mps348)

**Comment by afalenski** [comment]
Done.
