### ISSUE TITLE
Adjust and add tests to server for the new AVV mibi-portal

### ISSUE THREAD

**Issue by birgitlewicki** [SiLeBAT/mibi-portal-server#354]
As a developer I would like to have correctly running tests that check the custom validation functions that are implemented for the AVV DatA catalogs and the new ZSP2024 structure.

A significant part of the tests in customValidatorFunctions.spec.ts are commented out and need to be adapted after implementation of excel sheet v17 and the the new ZSP2024 structure.

`src/app/sampleManagement/domain/__tests__`:
  - [x] catalog.entity.spec.ts
  - [x] avvcatalog.entity.spec.ts
  - [x] customAutoCorrectionFunctions.spec.ts
  - [x] customValidatorFunctions.spec.ts

`src/app/sampleManagement/application/__tests__`:
  - [x] nrl.spec.ts
  - [x] validateSamples.spec.ts

**Comment by dptolle** [comment]
@birgitlewicki There's a few issues with this ticket:
- its scope can & should be reduced, spilling it up into separate tasks if need be
- it needs to be re-estimated.

Let's discuss this on Monday.
