### ISSUE TITLE
Adjust PDF to AVVDatA Einsendebogen template

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-server#360]
As a user I would like to receive a PDF with at least 10 data rows per page so that I do not have to print 10 pages if I want to send 15 samples to BfR. The AVVDatA codes and texts are much longer so that - in the current Einsendebogen - only 2-4 data rows fit on one page.

- Columns "Erreger (Code oder Text [...])" and "Matrix / Tiere (Freitext)" shall be wide and the whole text shall be displayed with word-wrap. For other columns between "Ort der Probenahme" and "Bemerkung" the text shall be displayed with word-wrap, but if the row height would become greater than that of Erreger or Matrix, the text shall be truncated and end with "...".
- Relative column widths: 
Column number   Column width
9	5,57
3	5,86
11	6,57
8	8
12	8
14	8
15	8
16	8
18	8
1	9,14
5	9,43
6	9,43
7	9,43
2	9,57
10	9,57
17	9,86
20	10,71
21	10,71
19	11,29
4	14,57
13	32,29
- Delete methods "Zoonosen-Monitoring..." and "Phagentypisierung".
- Make the textbox "Vergleiche mit humanen Isolaten" twice as tall  (see PDF example).
- Mind the fat cell borders around certain columns and around the headings (see PDF example).
- Mind the changed heading for "Tiere Code" and "Matrix Code" (see PDF example).
- Add a bit more space between the last sentence on the first page and the sentence before.

Example PDF was sent via email on 16.10.2023@15:50.

**Comment by birgitlewicki** [comment]
- The requested points are implemented and deployed on qa.
- The changed headings for "Tiere Code" and "Matrix Code" are changed in the PDF but not yet in the data grid UI of the mibi-portal.
 - The 12 samples of the current excel sheet example fit on one PDF page.
 
Please test

**Comment by afalenski** [comment]
PDF tests will be done in mpc545
