### ISSUE TITLE
Popup message on AVV portal if wrong version of the Einsendebogen is used

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-server#361]
As a user I would like to be informed that I use the wrong Einsendebogen in the AVV portal.

- If the user uploads an Einsendebogen v16 or earlier in AVV MiBi-Portal (soon at https://mibi-portal.bfr.bund.de/), show popup message. 
- Setup the Einsendebogen check as such that not only v17 is accepted in the MiBi-Portal but all the following versions of the Einsendebogen, too.
- Do not process this Einsendebogen; do not show the data grid.
- In the centre of the screen show a popup box (width like the textbox on the MiBi-Portal startpage) and grey out the rest of the MiBi-Portal.

Popup message:
Title: "Falsche Version des Einsendebogens verwendet"

Text:
"Sie haben versucht, einen Einsendebogen der Version [Versionsnummer] hochzuladen. Version 16 und frühere Versionen des Einsendebogens sind für ADV-codierte Daten gedacht. Wenn Sie ADV-codierte Daten an das BfR melden möchten, laden Sie Ihren Einsendebogen bitte im ADV-MiBi-Portal hoch: [https://mibi-portal-adv.bfr.bund.de](https://mibi-portal-adv.bfr.bund.de)

Dieses MiBi-Portal hier ist ausschließlich für AVV DatA-codierte Daten vorgesehen, die Sie über den Einsendebogen ab Version 17 hier hochladen können."

(In a later ticket the link to Einsendebogen v17 will be added to this text.)

Ticket in addition to [mps359](https://app.zenhub.com/workspaces/mibi-portal-5a817089b72527484e410a5a/issues/gh/silebat/mibi-portal-server/359)

**Comment by birgitlewicki** [comment]
Implemented with the current `nolar-dev` link. This will be changed when we'll have the `mibi-portal-adv` link

**Comment by afalenski** [comment]
Looks very nice!
- Version of uploaded Einsendebogen stated correctly
- Appears if Einsendebogen v16 or v15 is uploaded
- Does not appear if Einsendebogen v17 is uploaded
- Data grid is not shown for v16 or v15.

**Please change:**
- Omit the empty spaces before and after the hyphens, please ("...ADV - codierte..." -> "...ADV-codierte..." and 5 other times).

**Please add:**
- Add a button below the text, position in centre: "Zurück zum AVV-MiBi-Portal"; or if this does not comply with Angular material, then name it simply "Zurück".

**Comment by birgitlewicki** [comment]
Popup message text changed and cancel button added.

**Comment by afalenski** [comment]
- [x] Hyphens without empty spaces
- [x] Button added and works.
Done.
