### ISSUE TITLE
Adopt Lims Excel sheet to new v17 Lims requirements.

### ISSUE THREAD

**Issue by birgitlewicki** [SiLeBAT/mibi-portal-server#362]
As NRL user I would like to receive an Einsendebogen containing AVV codes and AVV texts because the LIMS does not translate the codes anymore.

- Use the Einsendebogen-v17[Date]_fuerLIMS.xlsx sent by AF on 15.11.2023@12:09 as template
- In general, data visible in the client plus metadata should be put into this Einsendebogen as before.
- For the additional text columns: Put the complete translation of the AVV code (including the facette catalogue name) into the new AVV text columns (do not abbreviate). The result should look like in the example data rows which were sent (see above).
- Text translations for codes from AVV catalogues 303, 313, 316, 319, 322, 326 328, 328, 339 are needed in addition to the previous solution.
- AVV catalogue 313 is special: The needed translation text is found after attributeid 1401 (child of the respective code in the AVV XML).
- Send this kind of file to BfR labs when a user clicks on the "Senden" button in the MiBi-Portal.
- If the text in a free text cell is 100% identical to the translated code, delete the text in the free text cell:
   - 324 Erreger (Text): delete if 100% duplicate of Text aus AVV 324
   - 313 Ort der Probenahme (Text): #mpc514 -> if ZIP and city is empty generate text from ADV/AVV Code; this now leads to duplicated text in the NRL Excel; proposal: #mpc514 is obsolete, delete if 100% duplicated of Text aus AVV 313
   - 339/319 Tiere/Matrix (Text): delete the 100% duplicate part(s) from Tiere and Matrix Text aus AVV 339 and/or AVV 319, user custom text should stay
   - 316 Primärproduktion: no free text column
   - 322/326 Kontrollpr./Untersuchungspr. (Text): same situation as with Tiere/Matrix (Text)
   - 303 Betriebsart (Text): delete if duplicated
   - 328 Programm: no free text column

**Comment by birgitlewicki** [comment]
Implemented as requested.

Remark for the fields "Tiere / Matrix (Text)" and "Kontrollprogramm / Unterscuchungsgrund (Text)":
The generated catalog text(s) is/are removed from the 2 fields if they exist as identical versions in these fields. In the case that these texts are separated by additional characters like pipe, comma or something similar these additional characters remains in these fields.

**Comment by afalenski** [comment]
Great! 
- Codes are translated.
- Texts are deleted if identical to AVV DatA text
Done.
