### ISSUE TITLE
Wizard does not contain Text at "sonstiges" nor at "Vergleiche mit humanen Isolaten

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-server#364]
- Upload an Einsendebogen v17 containing text at "sonstiges" and at "Vergleiche mit humanen Isolaten which is for only one BfR lab.
- Login and click on "Senden" in the light blue bar in order to display the wizard.
The wizard does not contain the texts. 

Expected: In the productive (ADV) MiBi-Portal these texts are in the wizard if the Einsendebogen contains pathogens for the identical BfR lab. If there are pathogens for several labs these texts are missing.

**Comment by birgitlewicki** [comment]
Implemented as following:

- When uploading an Excel sheet v17 with one or more samples belonging to one single nrl that have text in the "Erreger" column the yellow text at "sonstiges" and at "Vergleiche mit..." appears in the wizard.
- In the case that the "Erreger" column contains the pathogen code from the 324 catalog the text of the yellow boxes does not appear in the wizard. The same "feature" exists on the productive system.

**Comment by afalenski** [comment]
- The text at "Sonstiges" and "Vergleiche mit humanen Isolaten" from the uploaded Einsendebogen containing only pathogen texts for one NRL is in the wizard.
- If there are pathogens for more than one BfR lab in the uploaded Einsendebogen, there is no text at "Sonstiges" or "Vergleiche mit humanen Isolaten" in the wizard (good).
Done.
