### ISSUE TITLE
Exchange RegEx in NRL data table

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-server#365]
As a MiBi-Portal user I would like to be able to send pathogens with new AVV324 names to BfR.

Change RegEx for every lab according to the email sent to BL on 04.01.2024

**Comment by birgitlewicki** [comment]
deployed on qa, please test

**Comment by afalenski** [comment]
Tested with 3 different test sheets. All pathogens were found, all labs were displayed.
Great!
Done.

**Comment by birgitlewicki** [comment]
Deployed on productive AVV portal
