### ISSUE TITLE
Create a "Diff"-View for all changes done online

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/mibi-portal-server#38]
As a Portal user I would like to know what changes I have done online ( & auto-corrected) in order to go back to my LIMS administrator and show him which data needs to be altered for automatic reporting

NB: The downloaded excel file should only mark-up changed fields
Colour: #0de5cf

**Comment by dptolle** [comment]
Issue moved to [SiLeBAT/mibi-portal-client #129](https://github.com/SiLeBAT/mibi-portal-client/issues/129) via [**ZenHub**](https://www.zenhub.com/)
