### ISSUE TITLE
Refactor the GET NRL controller to use the parse REST API

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/mibi-portal-server#388]

**Comment by dptolle** [comment]
@afalenski RE: Testing.  The first call to the API is done during initial web-app load, so ideally no error should be thrown there.  The data that the API provides is NRL id's and the analysis procedures they offer  - I guess they are used inside our stepper as part of our send-off wizard.

**Comment by afalenski** [comment]
NRLs are loaded, sample analysis methods are displayed.
Done.
