### ISSUE TITLE
create JS based plausibility checker class

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/mibi-portal-server#4]
As a MIBI User I want my uploaded or otherwise generated data validated
- against a JS based plausibility checker class
in order to ameliorate my data set.

Error codes: [Mibi-Portal_Fehlermeldungen_AF_OnlyCodes.xlsx](https://github.com/SiLeBAT/epi-lab-server/files/1737475/Mibi-Portal_Fehlermeldungen_AF_OnlyCodes.xlsx)

**Comment by dptolle** [comment]
Error Number 8 is not implemented in this ticket
