### ISSUE TITLE
Case insensitive handling of email addresses

### ISSUE THREAD

**Issue by birgitlewicki** [SiLeBAT/mibi-portal-server#43]
As a mibi portal user I want my email address to be handled in a case insensitive manner.
This works for the login procedure.

I still can register twice with the same email if it is written in different cases,
e.g. a@b and A@b is handled as two different emails. This should not be the case.

**Comment by afalenski** [comment]
Now I can see the toaster message. Registering with an already registered email address is not possible anymore. Done!
