### ISSUE TITLE
Refactor the POST Submitted controller to use the parse cloud code

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/mibi-portal-server#441]

**Comment by afalenski** [comment]
- The portal starts and validates the test sheet; the wizard works.
- Both user email and lab email are sent and contain the expected PDF/Excel file.
- Registration works and emails are fine.
- Password reset works. Emails are fine except for the disappeared button, but this is stated in the review of mps435.
Done.

______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
Einsendebogen-v17_NRL-AR_TEST.xlsx

Browsers:
- Firefox 115.15.0esr (64-Bit)
