### ISSUE TITLE
Agent detection and correction

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/mibi-portal-server#53]
As a portal user I would like to be warned if the agent that I submitted (3rd column) is not listed in the associated ADV catalogue.

Note:
the following rules should apply:
0. trim the entered text
1. text is a number -> compare with ADV number
Relevant ADV16 codes:
'>= 302000 && < 306000 ||
'>= 500000 && < 1700000 ||
'>= 3402000 && < 3402080 ||
'>= 5500000 && < 6000000
Error message for valid ADV16 codes which are NOT within these four ranges: "Der verwendete Code codiert keinen Erreger, der am BfR untersucht wird."
2. text is not a number ->
  a. find perfect match in ADV catalogue
  b. special rules:
    - find match by adding "Genus " in front of the text
    - allow for special terms, e.g. "E. coli" -> "Escherichia coli", "STEC" -> "Escherichia coli Verotoxinbildende", "ESBL" -> "Escherichia coli ESBL-bildend"

     c. alter text by adding a space after each dot if there is none
       and apply fuzzy search with parameters as follows:
xxxxxxxxxxxxxxxxxxxx
var options = {
  id: "Text1",
  shouldSort: true,
  tokenize: true,
  includeScore: true,
  threshold: 0.6,
  location: 0,
  distance: 100,
  maxPatternLength: 100,
  minMatchCharLength: 1,
  keys: [
    {
        "name": "Text1",
        "weight": 0.9
    },
    {
        "name": "P-Code3",
        "weight": 0.1
    }
]
};
xxxxxxxxxxxxxxxxxxxx

If there is a perfect match (number or text) - nothing to colorize
If no perfect match:
- number: mark red
- text: mark red and offer
  - special rules result
  - top 20 (?) results from fuzzy search, which the portal user may choose from - and the user may also enter new text
The user needs to confirm/choose from the offered list if marked red!

**Comment by afalenski** [comment]
Here are the ADV16 codes relevant for the MiBi-Portal:

return 
	$ADV16_Int$ >= 500000 && $ADV16_Int$ < 1700000 ||
	$ADV16_Int$ >= 3402000 && $ADV16_Int$ < 3402080 ||
	$ADV16_Int$ >= 5500000 && $ADV16_Int$ < 6000000
;

With these limitations on the ADV16 list the auto-correction results above would not be possible, simply because the list would contain neither Boscalid nor Boldenon.

**Comment by afalenski** [comment]
2 and 3a work. But what about the fuzzy search (3b)? "E. coli" is not recognised and none of the 150 alias names in the attached test sheet.
[https://app.zenhub.com/files/121366790/798c71f5-d4f8-4245-a12e-fea2affb0d93/download](https://app.zenhub.com/files/121366790/798c71f5-d4f8-4245-a12e-fea2affb0d93/download)

**Comment by afalenski** [comment]
Pathogen aliases tested. Except for four entries the results of the fuzzy search are very good.
