### ISSUE TITLE
Optimize Fuzzy Search

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/mibi-portal-server#60]
Add following option to the fuse.js options:
 "matchAllTokens: true"

Add following aliases to the config file:
Escherichia coli Verotoxinbildende:  E.  coli STEC
Escherichia coli Verotoxinbildende:  STEC
Escherichia coli Stx I-Toxinbildner: toxin stxI
Escherichia coli Verotoxinbildende:  vtec

If an alias is found, then it should be offered as a correction suggestion to the user alongside the Top 10 Fuzzy search results.

**Comment by draaw** [comment]
Looks good, but now only one result is shown in the Auswahlbox

**Comment by dptolle** [comment]
@draaw Yes, but it's the "correct" result.  The one determined by our alias'
