### ISSUE TITLE
Validation enhancement for duplicate Ids (AVV and normal)

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/mibi-portal-server#67]
As a portal user I need to have defined a unique sample by all three columns ("Ihre Probenummer", "Probenummer nach AVVData" and "Erreger")
Background: AVVData does not contain "Teilproben", but "Ihre Probenummer" may do.

Check error codes 6

**Comment by afalenski** [comment]
Testsheet covering combinations of Probenummer, AVVData and Erreger; explanations (sometimes long explanations) are in column 'Bemerkungen'.
[https://app.zenhub.com/files/121366790/ce619bad-ae48-4428-b4f4-54f86ef9b607/download](https://app.zenhub.com/files/121366790/ce619bad-ae48-4428-b4f4-54f86ef9b607/download)

**Comment by dptolle** [comment]
Not all error codes where available in the qa DB.
@afalenski Please re-test
