### ISSUE TITLE
Performance differences between Prod and QA portal

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/mibi-portal-server#74]
@afalenski commented on [Mon Nov 19 2018](https://github.com/SiLeBAT/mibi-portal-client/issues/151)

Please upload the test sheet (see slack message): In the productive portal it is validated after 2 seconds while the qa portal needs 16 seconds. Please reduce validation time.

**Comment by afalenski** [comment]
Splendid! What a performance boost!
