### ISSUE TITLE
Validation error: only for "Grund"-code 81 column "Verarbeitungszustand" is obligatory

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/mibi-portal-server#78]

**Comment by afalenski** [comment]
Either for "Grund"-code '81' or "Grund"-text 'Zoonosen-Monitoring - Planprobe' an entry in column "Verarbeitungszustand" is obligatory for "Betriebsart" starting with '4'.

**Comment by draaw** [comment]
the validator is still throwing an error when "Grund"="Planprobe"=10

**Comment by draaw** [comment]
sorry, wrong server. all fine!
