### ISSUE TITLE
Change the NRL-AR selector

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/mibi-portal-server#81]
@dptolle commented on [Wed Jan 16 2019](https://github.com/SiLeBAT/mibi-portal-client/issues/165)

See email for the updated list (from Alex 16/1/2019@10:28)

**Comment by afalenski** [comment]
The ADV16 agents shown below are not recognised as belonging to the NRL-AR. Strikingly they are exactly those agents which are represented by a general search word (like *enterococ*) in the file "NRL-Erreger-Filter_20190116.xlsx". Please adjust the agent <-> NRL matching function in the MiBi-Portal.

Enterobacteriaceae
Enterobacteriaceae ESBL-bildend
Enterobacteriaceae AmpC-bildend
Enterobacteriaceae Carbapenemase-bildend
Genus Enterobacter
Enterobacter aerogenes
Enterobacter cloacae

**Comment by dptolle** [comment]
@afalenski , @draaw :Regular Expressions are case-sensitive & the in the Excel-file supplied RegEx's do not cover capitalised Enterobacter or Enterococ* - should I make all the RegEx matching case insensitive, or add capitalised cases of Enterobacter & Enterococ*?

**Comment by draaw** [comment]
yes, case insensitivity should do nicely

**Comment by afalenski** [comment]
Much better, only "Enterobacteriaceae" is not recognised, yet.

**Comment by afalenski** [comment]
Some agents do not get a warning. See test sheet I sent to you via email (18.01.2019@11:45)
