### ISSUE TITLE
Different Probenummern in identical scientific notation are marked duplicates in MiBi-Portal

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/mibi-portal-server#85]
@afalenski commented on [Wed Dec 19 2018](https://github.com/SiLeBAT/mibi-portal-client/issues/157)

The attached Probeneinsendebogen shows the Probenummer in the scientific notation in lines 1+2 but both cells still contain the full Probenummer (which you can see if you click into the Excel cell). The MiBi-Portal imports the Probenummer as text which leads to an error for duplicate Probenummern. For the text this is true but not for the real Probenummern.
[mpc157_WissAnsichtProbenummern.xlsx](https://github.com/SiLeBAT/mibi-portal-client/files/2695383/mpc157_WissAnsichtProbenummern.xlsx)
Is this a bug or a potential feature?

**Comment by draaw** [comment]
is it possible to handle this issue the same way as described in mpc#156, i.e. giving this issue back to the user for approval?
requirement would be: the portal needs to be able to detect it. I would assume that this is possible in the following way: always when the format of a cell is not "Text", the user should be asked. Maybe this is too strong, it may be sufficient to have it column by column, meaning for this specific ticket: check first column of being of "Double" format - if yes, ask for user approval.

**Comment by afalenski** [comment]
This is not a problem anymore, thus it is not a bug in the current version. The MiBi-Portal imports the Probenummer and shows the complete number (no text import of scientific notation anymore). The warning for duplicate Probenummern appears. To be closed.
