### ISSUE TITLE
Update rules for AVV numbers

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/mibi-portal-server#87]
some AVV numbers are now more precise and need to be updated - see separate mail (27.04.19; 17:21)

**Comment by afalenski** [comment]
Login with a Bavarian account and upload the attached testsheet. 
- Rows 3, 4, 5 and 7 contain a correct Probenummer nach AVVData (the portal does a mistake in row 5, but we have ticket #283 for this)
- [ ] Row 8 contains a Probenummer nach AVVData from Rhineland-Palatinate. The MiBi-Portal should give a warning when being logged in with a Bavarian account.

[https://app.zenhub.com/files/121366790/90e8c312-3207-4eef-b4eb-2b3a54dbe315/download](https://app.zenhub.com/files/121366790/90e8c312-3207-4eef-b4eb-2b3a54dbe315/download)
