### ISSUE TITLE
Improve autotext suggestions for E. coli

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/mibi-portal-server#88]
@afalenski commented on [Wed Dec 19 2018](https://github.com/SiLeBAT/mibi-portal-client/issues/155)

If "E.coli, kommensal" is given in column "Erreger (Text aus ADV-Kat-Nr.16)", "Escherichia coli" should be shown in dropdown suggestions.
[mps53_autocorrection.xlsx](https://github.com/SiLeBAT/mibi-portal-client/files/2694518/mps53_autocorrection.xlsx)

DevNote: use alias, remove ',' and ' ' and do a lowercase beforehand

**Comment by afalenski** [comment]
Works. I can choose "Escherichia coli" if I enter "E.coli, kommensal".
