### ISSUE TITLE
Commenting before sending

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/mibi-portal-server#91]
@draaw commented on [Mon Jan 28 2019](https://github.com/SiLeBAT/mibi-portal-client/issues/173)

As a portal user I would like to add a comment to my data, that should be part of the mail that goes to the NRLs.

---

@dptolle commented on [Mon Feb 04 2019](https://github.com/SiLeBAT/mibi-portal-client/issues/173#issuecomment-460185666)

Requires new Server Major version.

**Comment by afalenski** [comment]
The user comment is in the email. However, the position in the email is not my first choice. I would prefer a little change in the wording and formatting:

- Replace "Absender Kommentar:" by "Mitteilung des Absenders an das BfR:"
- Place user comment between "Bitte bearbeiten Sie den Auftrag im Anhang." and "Absender:"
- Do not write "Das MiBi-Portal Team". We do not provide the data in the attachment, we are the silent service in the background. The NRLs should get the feeling that Mrs/Mr X from lab Y has sent them data.
- Please mind the different formatting of the sender information.

Example:
_Sehr geehrte Damen und Herren,_
_Bitte bearbeiten Sie den Auftrag im Anhang._

NEW: _Mitteilung des Absenders an das BfR:_
NEW: _Dies ist ein Test von Alex. Die E-Mail sollte meine Nachricht enthalten. Bla bla bla.... Die Daten sind Testdaten und gehören nicht ins BfR-LIMS._

_~~Absender:~~_
_Rednaxela Iksnelaf_  
_Bayerisches Landesamt für Gesundheit und Lebensmittelsicherheit_  
_Dienststelle Oberschleißheim_  
_Alexander.Falenski@bfr.bund.de_  
_~~Absender Kommentar:~~_

_~~Das MiBi-Portal Team~~_

@draaw : What is your opinion on these ideas?

**Comment by draaw** [comment]
I agree.
Additionally: the sender of the data also needs to have the comment within its e-mail - for "reproducibility" reasons.

**Comment by afalenski** [comment]
Bitte noch die beiden Rechtschreibfehler korrigieren:
- [ ] Punkt nach "... an das BfR gesendet"
- [ ] Komma nach "Bitte vergessen Sie nicht"
Ansonsten sieht es sehr gut aus!

**Comment by afalenski** [comment]
Why is this ticket in the Review/QA lane? There are no changes in the email. Please do the small changes stated above.

**Comment by dptolle** [comment]
@afalenski QA was hosting an older Version?  Could you please re-test.

**Comment by afalenski** [comment]
Wonderful! Both the email to the NRL and the email to the sender are very nice, now. Done.
