### ISSUE TITLE
Add Sender (Place)  & Receiver (NRL) to Job email subject line

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/mibi-portal-server#92]

**Comment by draaw** [comment]
The subject of the mail now reads: "undefined an".
What about: "Neuer Auftrag von <X> an <Y>"?
If something is "undefined" it should read more human-friendly, e.g. "<unbekannt>" or "?"

**Comment by dptolle** [comment]
Message should be: 'Neuer Auftrag von X an Y'
undefined or '' should be:\<unbekannt\>
